=== bobwolff68/neuron/Neuron/code/tools/ubrain/libxml/ubrain.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT neuron-ubrain (MACROGROUP)+>

<!ELEMENT MACROGROUP (STATUS|CONNECT|SF|LOCAL|SETUP)*>

<!ELEMENT STATUS (FACTORIES|ENTITIES|ENDPOINTS)+>
  <!ELEMENT FACTORIES EMPTY>
  <!ELEMENT ENTITIES EMPTY>
  <!ELEMENT ENDPOINTS EMPTY>

<!ELEMENT CONNECT EMPTY>
	<!ATTLIST CONNECT srcname CDATA #REQUIRED>
	<!ATTLIST CONNECT srcip CDATA #REQUIRED>
	<!ATTLIST CONNECT destip CDATA #REQUIRED>

<!ELEMENT SF (ADDSESSION|ADDENTITY|DELETEENTITY|DELETESESSION|DELETEFACTORY)+>
  <!ELEMENT ADDSESSION EMPTY>
	<!ATTLIST ADDSESSION sfid CDATA #REQUIRED>
	<!ATTLIST ADDSESSION sessid CDATA #REQUIRED>
	<!ATTLIST ADDSESSION sessionname CDATA "">
  <!ELEMENT ADDENTITY EMPTY>
	<!ATTLIST ADDENTITY sfid CDATA #REQUIRED>
	<!ATTLIST ADDENTITY sessid CDATA #REQUIRED>
	<!ATTLIST ADDENTITY entid CDATA #REQUIRED>
	<!ATTLIST ADDENTITY enttype (RP | FILESOURCE | DECODESINK) #REQUIRED>
	<!ATTLIST ADDENTITY entname CDATA "">
  <!ELEMENT DELETEENTITY EMPTY>
	<!ATTLIST DELETEENTITY sfid CDATA #REQUIRED>
	<!ATTLIST DELETEENTITY sessid CDATA #REQUIRED>
	<!ATTLIST DELETEENTITY entid CDATA #REQUIRED>
  <!ELEMENT DELETESESSION EMPTY>
	<!ATTLIST DELETESESSION sfid CDATA #REQUIRED>
	<!ATTLIST DELETESESSION sessid CDATA #REQUIRED>
  <!ELEMENT DELETEFACTORY EMPTY>
	<!ATTLIST DELETEFACTORY sfid CDATA #REQUIRED>

<!ELEMENT LOCAL (CREATESF|CREATESESSION|REMOVESESSION|REMOVESF|KILLSF)+>
  <!ELEMENT CREATESF EMPTY>
	<!ATTLIST CREATESF sfipaddress CDATA #REQUIRED>
	<!ATTLIST CREATESF sfid CDATA #REQUIRED>
	<!ATTLIST CREATESF sfname CDATA "">
  <!ELEMENT CREATESESSION EMPTY>
	<!ATTLIST CREATESESSION sessid CDATA #REQUIRED>
	<!ATTLIST CREATESESSION sessionname CDATA "">
  <!ELEMENT REMOVESESSION EMPTY>
	<!ATTLIST REMOVESESSION sessid CDATA #REQUIRED>
  <!ELEMENT REMOVESF EMPTY>
	<!ATTLIST REMOVESF sfid CDATA #REQUIRED>
  <!ELEMENT KILLSF EMPTY>
	<!ATTLIST KILLSF sfipaddress CDATA #REQUIRED>

<!ELEMENT SETUP (CREATEKEYPAIR|SENDPUBLICKEY|TESTAUTHENTICATION|VERBOSITY)+>
  <!ELEMENT CREATEKEYPAIR EMPTY>
  <!ELEMENT SENDPUBLICKEY CDATA>
  <!ELEMENT TESTAUTHENTICATION CDATA>
  <!ELEMENT VERBOSITY EMPTY> 
	<!ATTLIST VERBOSITY level CDATA #REQUIRED>

=== bobwolff68/neuron/sprint0-rev271/tools/ubrain/libxml/script.xml
<?xml version="1.0"?>
<!DOCTYPE neuron-ubrain SYSTEM "ubrain.dtd">
<neuron-ubrain>
<MACROGROUP>
  <SETUP>
    <VERBOSITY level="14"/>
  </SETUP>
  <STATUS>
    <FACTORIES/>
    <ENTITIES/>
  </STATUS>
  <LOCAL>
    <CREATESF sfid="1122" sfipaddress="192.168.46.78" sfname="Factory in Dallas TX" />
    <CREATESESSION sessid="1" sessionname="Engineering Status Conference" />
  </LOCAL>
  <SF>
    <ADDSESSION sfid="1122" sessid="1" sessionname="Engineering Status Conference" />
    <ADDENTITY sfid="1122" sessid="1" entid="1001" enttype="RP" entname="First RP Entity" />
  </SF>
</MACROGROUP>
</neuron-ubrain>
